### ISSUE TITLE
Is there a way to run tzcronjob right away?

### ISSUE THREAD

**Issue by wonizz** [hiddeco/cronjobber#55] opened 2022-09-13 06:36 UTC
As you know, in cronjob, you can create jobs through --from.
However, tzcronjob seems impossible. Is there a way?

**Comment by hiddeco** [comment] 2022-09-13 07:39
Duplicate of https://github.com/hiddeco/cronjobber/issues/21

**Closed by hiddeco** 2022-09-13 07:39 UTC
